USE [master]
GO
/****** Object:  Database [QuanLyThuVien_K235480106057]    Script Date: 5/3/2026 11:10:01 AM ******/
CREATE DATABASE [QuanLyThuVien_K235480106057]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyThuVien_K235480106057', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\QuanLyThuVien_K235480106057.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyThuVien_K235480106057_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\QuanLyThuVien_K235480106057_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyThuVien_K235480106057].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET RECOVERY FULL 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET  MULTI_USER 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'QuanLyThuVien_K235480106057', N'ON'
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET QUERY_STORE = ON
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QuanLyThuVien_K235480106057]
GO
/****** Object:  UserDefinedFunction [dbo].[fn_ThongKeMuon]    Script Date: 5/3/2026 11:10:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[fn_ThongKeMuon]()
RETURNS @Result TABLE
(
    MaSV INT,
    SoLanMuon INT
)
AS
BEGIN
    INSERT INTO @Result
    SELECT MaSV, COUNT(*)
    FROM PhieuMuon
    GROUP BY MaSV;

    RETURN;
END;
GO
/****** Object:  UserDefinedFunction [dbo].[fn_TinhSoNgayMuon]    Script Date: 5/3/2026 11:10:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[fn_TinhSoNgayMuon]
(
    @NgayMuon DATE,
    @NgayTra DATE
)
RETURNS INT
AS
BEGIN
    RETURN DATEDIFF(DAY, @NgayMuon, @NgayTra);
END;
GO
/****** Object:  Table [dbo].[Sach]    Script Date: 5/3/2026 11:10:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sach](
	[MaSach] [int] NOT NULL,
	[TenSach] [nvarchar](100) NULL,
	[SoLuong] [int] NULL,
	[GiaTien] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  UserDefinedFunction [dbo].[fn_SachCon]    Script Date: 5/3/2026 11:10:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[fn_SachCon]()
RETURNS TABLE
AS
RETURN
(
    SELECT * FROM Sach WHERE SoLuong > 0
);
GO
/****** Object:  Table [dbo].[PhieuMuon]    Script Date: 5/3/2026 11:10:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhieuMuon](
	[MaPM] [int] NOT NULL,
	[MaSV] [int] NULL,
	[MaSach] [int] NULL,
	[NgayMuon] [date] NULL,
	[NgayTra] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaPM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SinhVien]    Script Date: 5/3/2026 11:10:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SinhVien](
	[MaSV] [int] NOT NULL,
	[TenSV] [nvarchar](50) NULL,
	[Lop] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[PhieuMuon] ([MaPM], [MaSV], [MaSach], [NgayMuon], [NgayTra]) VALUES (1, 1, 1, CAST(N'2025-01-10' AS Date), CAST(N'2026-01-10' AS Date))
INSERT [dbo].[PhieuMuon] ([MaPM], [MaSV], [MaSach], [NgayMuon], [NgayTra]) VALUES (2, 2, 2, CAST(N'2025-02-15' AS Date), CAST(N'2026-02-15' AS Date))
INSERT [dbo].[PhieuMuon] ([MaPM], [MaSV], [MaSach], [NgayMuon], [NgayTra]) VALUES (3, 3, 3, CAST(N'2025-03-20' AS Date), CAST(N'2026-03-20' AS Date))
GO
INSERT [dbo].[Sach] ([MaSach], [TenSach], [SoLuong], [GiaTien]) VALUES (1, N'Tôi thấy hoa vàng trên cỏ xanh', 1, 50000.0000)
INSERT [dbo].[Sach] ([MaSach], [TenSach], [SoLuong], [GiaTien]) VALUES (2, N'Nhà giả kim', 7, 60000.0000)
INSERT [dbo].[Sach] ([MaSach], [TenSach], [SoLuong], [GiaTien]) VALUES (3, N'Tuổi trẻ đáng giá bao nhiêu', 4, 70000.0000)
GO
INSERT [dbo].[SinhVien] ([MaSV], [TenSV], [Lop]) VALUES (1, N'Nguyễn Văn A', N'K59KMT')
INSERT [dbo].[SinhVien] ([MaSV], [TenSV], [Lop]) VALUES (2, N'Trần Văn B', N'K59KMT')
INSERT [dbo].[SinhVien] ([MaSV], [TenSV], [Lop]) VALUES (3, N'Lê Văn C', N'K59KMT')
GO
ALTER TABLE [dbo].[PhieuMuon]  WITH CHECK ADD FOREIGN KEY([MaSach])
REFERENCES [dbo].[Sach] ([MaSach])
GO
ALTER TABLE [dbo].[PhieuMuon]  WITH CHECK ADD FOREIGN KEY([MaSV])
REFERENCES [dbo].[SinhVien] ([MaSV])
GO
ALTER TABLE [dbo].[Sach]  WITH CHECK ADD CHECK  (([SoLuong]>=(0)))
GO
/****** Object:  Trigger [dbo].[trg_GiamSoLuongSach]    Script Date: 5/3/2026 11:10:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[trg_GiamSoLuongSach]
ON [dbo].[PhieuMuon]
AFTER INSERT
AS
BEGIN
    UPDATE Sach
    SET SoLuong = SoLuong - 1
    WHERE MaSach IN (SELECT MaSach FROM inserted);
END;
GO
ALTER TABLE [dbo].[PhieuMuon] ENABLE TRIGGER [trg_GiamSoLuongSach]
GO
/****** Object:  Trigger [dbo].[trg_KiemTraSoLuong]    Script Date: 5/3/2026 11:10:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[trg_KiemTraSoLuong]
ON [dbo].[Sach]
AFTER UPDATE
AS
BEGIN
    IF EXISTS (SELECT * FROM inserted WHERE SoLuong < 0)
    BEGIN
        PRINT N'Lỗi: Số lượng sách không hợp lệ!';
        ROLLBACK TRANSACTION;
    END
END;
GO
ALTER TABLE [dbo].[Sach] ENABLE TRIGGER [trg_KiemTraSoLuong]
GO
USE [master]
GO
ALTER DATABASE [QuanLyThuVien_K235480106057] SET  READ_WRITE 
GO
